"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "fr" | "es" | "ar" | "pt" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (k) => k,
  dir: "ltr",
});

export function useLanguage() {
  return useContext(LanguageContext);
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.destinations": "Destinations",
    "nav.testimonials": "Testimonials",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.book": "Book Consultation",
    "nav.signin": "Sign In",
    "nav.pricing": "Pricing",
    "nav.faq": "FAQ",
    "hero.badge": "#1 International Immigration Agency",
    "hero.title": "Your Trusted Partner to Succeed in Your Immigration Project",
    "hero.subtitle": "We guide students, professionals, and visitors through their immigration process to France, Canada, and Luxembourg — with expert precision and personal care.",
    "hero.cta1": "Free Consultation",
    "hero.cta2": "Our Services",
    "hero.stat1": "97% Success Rate",
    "hero.stat2": "10+ Years Experience",
    "hero.stat3": "24/7 Support",
    "stats.cases": "Cases Processed",
    "stats.cases_sub": "Successfully completed",
    "stats.success": "Success Rate",
    "stats.success_sub": "Visa approvals",
    "stats.years": "Years Experience",
    "stats.years_sub": "In immigration consulting",
    "stats.support": "Client Support",
    "stats.support_sub": "Always available for you",
    "about.badge": "Why Choose Us",
    "about.title": "Why Choose TRAVEL AGENCY?",
    "about.p1": "TRAVEL AGENCY is a premier immigration consulting firm specializing in helping students, professionals, and families achieve their international dreams.",
    "about.p2": "Our mission is to make your international project simple, secure, and accessible — from the very first consultation to your successful arrival.",
    "about.cta": "Learn More About Us",
    "services.badge": "Our Services",
    "services.title": "Comprehensive Immigration Solutions",
    "services.sub": "Tailored services for every type of immigration project, backed by a decade of expertise and a 97% success rate.",
    "services.student": "Student Immigration",
    "services.work": "Professional Immigration",
    "services.visitor": "Visitor Visa",
    "services.learn": "Learn More",
    "process.badge": "How It Works",
    "process.title": "Our Proven 5-Step Process",
    "process.sub": "A clear, transparent, and efficient methodology developed over 10+ years.",
    "process.s1": "Profile Evaluation",
    "process.s2": "File Preparation",
    "process.s3": "Application Submission",
    "process.s4": "Interview Preparation",
    "process.s5": "Visa Obtained",
    "dest.badge": "Destinations",
    "dest.title": "Your Dream Destinations",
    "dest.sub": "Three world-class destinations. Infinite opportunities. One expert guide to take you there.",
    "dest.discover": "Discover",
    "contact.title": "Get in Touch",
    "contact.cta": "Book Free Consultation",
    "common.success_rate": "97% Success Rate",
    "common.loading": "Loading...",
    "common.submit": "Submit",
    "footer.tagline": "Together toward your international success",
    "footer.newsletter.title": "Stay Updated with Immigration News",
    "footer.newsletter.sub": "Get the latest visa updates, policy changes, and success stories.",
    "footer.newsletter.btn": "Subscribe",
  },

  fr: {
    "nav.home": "Accueil",
    "nav.about": "À Propos",
    "nav.services": "Services",
    "nav.destinations": "Destinations",
    "nav.testimonials": "Témoignages",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.book": "Réserver une Consultation",
    "nav.signin": "Se Connecter",
    "nav.pricing": "Tarifs",
    "nav.faq": "FAQ",
    "hero.badge": "Agence Internationale d'Immigration #1",
    "hero.title": "Votre partenaire de confiance pour réussir votre projet d'immigration",
    "hero.subtitle": "Nous accompagnons les étudiants, travailleurs et visiteurs dans leurs démarches d'immigration vers la France, le Canada et le Luxembourg — avec expertise et accompagnement personnalisé.",
    "hero.cta1": "Consultation Gratuite",
    "hero.cta2": "Nos Services",
    "hero.stat1": "97% de Réussite",
    "hero.stat2": "10+ Ans d'Expérience",
    "hero.stat3": "Assistance 24/7",
    "stats.cases": "Dossiers Traités",
    "stats.cases_sub": "Complétés avec succès",
    "stats.success": "Taux de Réussite",
    "stats.success_sub": "Visas approuvés",
    "stats.years": "Années d'Expérience",
    "stats.years_sub": "En conseil en immigration",
    "stats.support": "Assistance Client",
    "stats.support_sub": "Toujours disponible pour vous",
    "about.badge": "Pourquoi Nous Choisir",
    "about.title": "Pourquoi choisir TRAVEL AGENCY ?",
    "about.p1": "TRAVEL AGENCY est une agence spécialisée dans l'accompagnement des projets d'immigration vers la France, le Canada et le Luxembourg.",
    "about.p2": "Notre mission est de rendre votre projet international simple, sécurisé et accessible — de la première consultation jusqu'à votre arrivée réussie.",
    "about.cta": "En Savoir Plus",
    "services.badge": "Nos Services",
    "services.title": "Solutions d'Immigration Complètes",
    "services.sub": "Services sur mesure pour chaque type de projet d'immigration, avec 97% de taux de réussite.",
    "services.student": "Immigration Étudiante",
    "services.work": "Immigration Professionnelle",
    "services.visitor": "Visa Visiteur",
    "services.learn": "En Savoir Plus",
    "process.badge": "Comment Ça Marche",
    "process.title": "Notre Processus Éprouvé en 5 Étapes",
    "process.sub": "Une méthodologie claire, transparente et efficace développée sur 10+ ans.",
    "process.s1": "Évaluation du profil",
    "process.s2": "Constitution du dossier",
    "process.s3": "Soumission de la demande",
    "process.s4": "Préparation à l'entretien",
    "process.s5": "Obtention du visa",
    "dest.badge": "Destinations",
    "dest.title": "Vos Destinations de Rêve",
    "dest.sub": "Trois destinations de classe mondiale. Des opportunités infinies. Un guide expert pour vous y conduire.",
    "dest.discover": "Découvrir",
    "contact.title": "Contactez-Nous",
    "contact.cta": "Consultation Gratuite",
    "common.success_rate": "97% de Réussite",
    "common.loading": "Chargement...",
    "common.submit": "Envoyer",
    "footer.tagline": "Ensemble vers votre réussite internationale",
    "footer.newsletter.title": "Restez informé des actualités immigration",
    "footer.newsletter.sub": "Recevez les dernières mises à jour sur les visas, changements de politique et histoires de succès.",
    "footer.newsletter.btn": "S'abonner",
  },

  es: {
    "nav.home": "Inicio",
    "nav.about": "Nosotros",
    "nav.services": "Servicios",
    "nav.destinations": "Destinos",
    "nav.testimonials": "Testimonios",
    "nav.blog": "Blog",
    "nav.contact": "Contacto",
    "nav.book": "Reservar Consulta",
    "nav.signin": "Iniciar Sesión",
    "nav.pricing": "Precios",
    "nav.faq": "Preguntas",
    "hero.badge": "Agencia de Inmigración Internacional #1",
    "hero.title": "Su socio de confianza para tener éxito en su proyecto de inmigración",
    "hero.subtitle": "Guiamos a estudiantes, profesionales y visitantes en su proceso de inmigración a Francia, Canadá y Luxemburgo — con precisión experta y cuidado personal.",
    "hero.cta1": "Consulta Gratuita",
    "hero.cta2": "Nuestros Servicios",
    "hero.stat1": "97% de Éxito",
    "hero.stat2": "10+ Años de Experiencia",
    "hero.stat3": "Soporte 24/7",
    "stats.cases": "Casos Procesados",
    "stats.cases_sub": "Completados con éxito",
    "stats.success": "Tasa de Éxito",
    "stats.success_sub": "Aprobaciones de visa",
    "stats.years": "Años de Experiencia",
    "stats.years_sub": "En consultoría de inmigración",
    "stats.support": "Soporte al Cliente",
    "stats.support_sub": "Siempre disponible para usted",
    "about.badge": "Por Qué Elegirnos",
    "about.title": "¿Por qué elegir TRAVEL AGENCY?",
    "about.p1": "TRAVEL AGENCY es una firma de consultoría de inmigración de primer nivel especializada en ayudar a estudiantes, profesionales y familias a lograr sus sueños internacionales.",
    "about.p2": "Nuestra misión es hacer que su proyecto internacional sea simple, seguro y accesible — desde la primera consulta hasta su llegada exitosa.",
    "about.cta": "Más Información",
    "services.badge": "Nuestros Servicios",
    "services.title": "Soluciones Integrales de Inmigración",
    "services.sub": "Servicios adaptados para cada tipo de proyecto migratorio, respaldados por una década de experiencia y un 97% de tasa de éxito.",
    "services.student": "Inmigración Estudiantil",
    "services.work": "Inmigración Profesional",
    "services.visitor": "Visa de Visitante",
    "services.learn": "Saber Más",
    "process.badge": "Cómo Funciona",
    "process.title": "Nuestro Proceso Probado de 5 Pasos",
    "process.sub": "Una metodología clara, transparente y eficiente desarrollada durante más de 10 años.",
    "process.s1": "Evaluación del Perfil",
    "process.s2": "Preparación del Expediente",
    "process.s3": "Presentación de la Solicitud",
    "process.s4": "Preparación para la Entrevista",
    "process.s5": "Visa Obtenida",
    "dest.badge": "Destinos",
    "dest.title": "Sus Destinos de Ensueño",
    "dest.sub": "Tres destinos de clase mundial. Infinitas oportunidades. Un guía experto para llevarle allí.",
    "dest.discover": "Descubrir",
    "contact.title": "Contáctenos",
    "contact.cta": "Consulta Gratuita",
    "common.success_rate": "97% de Éxito",
    "common.loading": "Cargando...",
    "common.submit": "Enviar",
    "footer.tagline": "Juntos hacia su éxito internacional",
    "footer.newsletter.title": "Manténgase Actualizado con Noticias de Inmigración",
    "footer.newsletter.sub": "Reciba las últimas actualizaciones de visas, cambios de política e historias de éxito.",
    "footer.newsletter.btn": "Suscribirse",
  },

  ar: {
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.services": "الخدمات",
    "nav.destinations": "الوجهات",
    "nav.testimonials": "الشهادات",
    "nav.blog": "المدونة",
    "nav.contact": "تواصل معنا",
    "nav.book": "احجز استشارة",
    "nav.signin": "تسجيل الدخول",
    "nav.pricing": "الأسعار",
    "nav.faq": "الأسئلة الشائعة",
    "hero.badge": "وكالة الهجرة الدولية الأولى",
    "hero.title": "شريكك الموثوق للنجاح في مشروع الهجرة الخاص بك",
    "hero.subtitle": "نرشد الطلاب والمهنيين والزوار في إجراءات الهجرة إلى فرنسا وكندا ولوكسمبورغ — بخبرة احترافية ورعاية شخصية.",
    "hero.cta1": "استشارة مجانية",
    "hero.cta2": "خدماتنا",
    "hero.stat1": "نسبة نجاح 97%",
    "hero.stat2": "أكثر من 10 سنوات خبرة",
    "hero.stat3": "دعم 24/7",
    "stats.cases": "ملفات تمت معالجتها",
    "stats.cases_sub": "أُنجزت بنجاح",
    "stats.success": "نسبة النجاح",
    "stats.success_sub": "قبول التأشيرات",
    "stats.years": "سنوات الخبرة",
    "stats.years_sub": "في استشارات الهجرة",
    "stats.support": "دعم العملاء",
    "stats.support_sub": "متاحون دائماً لك",
    "about.badge": "لماذا تختارنا",
    "about.title": "لماذا تختار TRAVEL AGENCY؟",
    "about.p1": "TRAVEL AGENCY شركة رائدة في استشارات الهجرة متخصصة في مساعدة الطلاب والمهنيين والعائلات لتحقيق أحلامهم الدولية.",
    "about.p2": "مهمتنا هي جعل مشروعك الدولي بسيطاً وآمناً وفي متناول الجميع — من أول استشارة حتى وصولك بنجاح.",
    "about.cta": "اعرف المزيد عنّا",
    "services.badge": "خدماتنا",
    "services.title": "حلول هجرة شاملة",
    "services.sub": "خدمات مخصصة لكل نوع من مشاريع الهجرة، مدعومة بعقد من الخبرة ونسبة نجاح 97%.",
    "services.student": "هجرة الطلاب",
    "services.work": "الهجرة المهنية",
    "services.visitor": "تأشيرة الزيارة",
    "services.learn": "اعرف المزيد",
    "process.badge": "كيف يعمل ذلك",
    "process.title": "عمليتنا المثبتة من 5 خطوات",
    "process.sub": "منهجية واضحة وشفافة وفعّالة طوّرناها على مدى أكثر من 10 سنوات.",
    "process.s1": "تقييم الملف الشخصي",
    "process.s2": "إعداد الملف",
    "process.s3": "تقديم الطلب",
    "process.s4": "التحضير للمقابلة",
    "process.s5": "الحصول على التأشيرة",
    "dest.badge": "الوجهات",
    "dest.title": "وجهاتك الحلم",
    "dest.sub": "ثلاث وجهات عالمية. فرص لا تنتهي. دليل خبير واحد يأخذك إلى هناك.",
    "dest.discover": "اكتشف",
    "contact.title": "تواصل معنا",
    "contact.cta": "احجز استشارة مجانية",
    "common.success_rate": "97% نسبة النجاح",
    "common.loading": "جار التحميل...",
    "common.submit": "إرسال",
    "footer.tagline": "معاً نحو نجاحك الدولي",
    "footer.newsletter.title": "ابقَ على اطلاع بأخبار الهجرة",
    "footer.newsletter.sub": "احصل على آخر تحديثات التأشيرات وتغييرات السياسات وقصص النجاح.",
    "footer.newsletter.btn": "اشترك",
  },

  pt: {
    "nav.home": "Início",
    "nav.about": "Sobre Nós",
    "nav.services": "Serviços",
    "nav.destinations": "Destinos",
    "nav.testimonials": "Depoimentos",
    "nav.blog": "Blog",
    "nav.contact": "Contato",
    "nav.book": "Agendar Consulta",
    "nav.signin": "Entrar",
    "nav.pricing": "Preços",
    "nav.faq": "Perguntas",
    "hero.badge": "Agência de Imigração Internacional #1",
    "hero.title": "Seu parceiro de confiança para ter sucesso no seu projeto de imigração",
    "hero.subtitle": "Orientamos estudantes, profissionais e visitantes no processo de imigração para a França, Canadá e Luxemburgo — com precisão especializada e cuidado pessoal.",
    "hero.cta1": "Consulta Gratuita",
    "hero.cta2": "Nossos Serviços",
    "hero.stat1": "97% de Sucesso",
    "hero.stat2": "10+ Anos de Experiência",
    "hero.stat3": "Suporte 24/7",
    "stats.cases": "Casos Processados",
    "stats.cases_sub": "Concluídos com sucesso",
    "stats.success": "Taxa de Sucesso",
    "stats.success_sub": "Aprovações de visto",
    "stats.years": "Anos de Experiência",
    "stats.years_sub": "Em consultoria de imigração",
    "stats.support": "Suporte ao Cliente",
    "stats.support_sub": "Sempre disponível para você",
    "about.badge": "Por Que Nos Escolher",
    "about.title": "Por que escolher a TRAVEL AGENCY?",
    "about.p1": "A TRAVEL AGENCY é uma empresa de consultoria de imigração premium especializada em ajudar estudantes, profissionais e famílias a realizarem seus sonhos internacionais.",
    "about.p2": "Nossa missão é tornar seu projeto internacional simples, seguro e acessível — desde a primeira consulta até sua chegada bem-sucedida.",
    "about.cta": "Saiba Mais Sobre Nós",
    "services.badge": "Nossos Serviços",
    "services.title": "Soluções Abrangentes de Imigração",
    "services.sub": "Serviços personalizados para cada tipo de projeto de imigração, respaldados por uma década de expertise e 97% de taxa de sucesso.",
    "services.student": "Imigração Estudantil",
    "services.work": "Imigração Profissional",
    "services.visitor": "Visto de Visitante",
    "services.learn": "Saiba Mais",
    "process.badge": "Como Funciona",
    "process.title": "Nosso Processo Comprovado de 5 Etapas",
    "process.sub": "Uma metodologia clara, transparente e eficiente desenvolvida ao longo de 10+ anos.",
    "process.s1": "Avaliação do Perfil",
    "process.s2": "Preparação do Dossiê",
    "process.s3": "Envio da Solicitação",
    "process.s4": "Preparação para a Entrevista",
    "process.s5": "Visto Obtido",
    "dest.badge": "Destinos",
    "dest.title": "Seus Destinos dos Sonhos",
    "dest.sub": "Três destinos de classe mundial. Oportunidades infinitas. Um guia especialista para levá-lo lá.",
    "dest.discover": "Descobrir",
    "contact.title": "Entre em Contato",
    "contact.cta": "Consulta Gratuita",
    "common.success_rate": "97% de Sucesso",
    "common.loading": "Carregando...",
    "common.submit": "Enviar",
    "footer.tagline": "Juntos rumo ao seu sucesso internacional",
    "footer.newsletter.title": "Fique Atualizado com Notícias de Imigração",
    "footer.newsletter.sub": "Receba as últimas atualizações de vistos, mudanças de políticas e histórias de sucesso.",
    "footer.newsletter.btn": "Assinar",
  },

  zh: {
    "nav.home": "首页",
    "nav.about": "关于我们",
    "nav.services": "服务",
    "nav.destinations": "目的地",
    "nav.testimonials": "客户评价",
    "nav.blog": "博客",
    "nav.contact": "联系我们",
    "nav.book": "预约咨询",
    "nav.signin": "登录",
    "nav.pricing": "价格",
    "nav.faq": "常见问题",
    "hero.badge": "#1 国际移民机构",
    "hero.title": "您移民项目成功的可信赖合作伙伴",
    "hero.subtitle": "我们以专业的精准度和个性化的关怀，指导学生、专业人士和访客完成前往法国、加拿大和卢森堡的移民程序。",
    "hero.cta1": "免费咨询",
    "hero.cta2": "我们的服务",
    "hero.stat1": "97% 成功率",
    "hero.stat2": "10+ 年经验",
    "hero.stat3": "24/7 支持",
    "stats.cases": "已处理案例",
    "stats.cases_sub": "成功完成",
    "stats.success": "成功率",
    "stats.success_sub": "签证批准",
    "stats.years": "年经验",
    "stats.years_sub": "移民咨询领域",
    "stats.support": "客户支持",
    "stats.support_sub": "随时为您服务",
    "about.badge": "为什么选择我们",
    "about.title": "为什么选择 TRAVEL AGENCY？",
    "about.p1": "TRAVEL AGENCY 是一家优质移民咨询公司，专门帮助学生、专业人士和家庭实现他们的国际梦想。",
    "about.p2": "我们的使命是让您的国际项目变得简单、安全且易于实现 — 从第一次咨询到成功抵达。",
    "about.cta": "了解更多",
    "services.badge": "我们的服务",
    "services.title": "全面的移民解决方案",
    "services.sub": "为每种移民项目量身定制服务，拥有十年专业经验和97%的成功率。",
    "services.student": "留学移民",
    "services.work": "职业移民",
    "services.visitor": "访客签证",
    "services.learn": "了解更多",
    "process.badge": "工作流程",
    "process.title": "我们经过验证的5步流程",
    "process.sub": "10年以上开发的清晰、透明、高效的方法论。",
    "process.s1": "档案评估",
    "process.s2": "文件准备",
    "process.s3": "申请提交",
    "process.s4": "面试准备",
    "process.s5": "获得签证",
    "dest.badge": "目的地",
    "dest.title": "您的梦想目的地",
    "dest.sub": "三个世界级目的地。无限机会。一位专家向导带您前往。",
    "dest.discover": "了解详情",
    "contact.title": "联系我们",
    "contact.cta": "预约免费咨询",
    "common.success_rate": "97% 成功率",
    "common.loading": "加载中...",
    "common.submit": "提交",
    "footer.tagline": "携手迈向您的国际成功",
    "footer.newsletter.title": "获取最新移民资讯",
    "footer.newsletter.sub": "获取最新签证更新、政策变化和成功案例。",
    "footer.newsletter.btn": "订阅",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageSt] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("ta-lang") as Language;
    if (saved && ["en", "fr", "es", "ar", "pt", "zh"].includes(saved)) {
      setLanguageSt(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageSt(lang);
    localStorage.setItem("ta-lang", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  };

  const t = (key: string): string => {
    return translations[language][key] ?? translations["en"][key] ?? key;
  };

  const dir: "ltr" | "rtl" = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}
